Improve the flow, added args for testing

diff --git a/aba b/aba
--- a/aba
+++ b/aba
@@ -5,96 +5,116 @@ cd $dir
 
 source scripts/include_all.sh
 
-# Include aba bin path and common scripts
-export PATH=$PWD/bin:$PWD/common/scripts:$PATH
-
-if [ "$1" = "--debug" -o "$1" = "-d" ]; then
-	export DEBUG_ABA=1
-	set -x
-	shift 
-fi
-
-cat message.txt
-
-############
-# Determine OCP version 
-
-if ! curl -sLI -o /dev/null https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/release.txt; then
-	echo "Error: Cannot access mirror.openshift.com"
-	exit 1
-fi
-
-## Get the latest stable OCP version number, e.g. 4.14.6
-stable_ver=$(curl -s https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/release.txt | tee /tmp/.release.txt | \
-	 egrep -o "Version: +[0-9]+\.[0-9]+\.[0-9]+" | awk '{print $2}')
-default_ver=$stable_ver
-
-# Extract the previous stable point version, e.g. 4.13.23
-stable_ver_point=`expr $(echo $stable_ver | grep ^4 | cut -d\. -f2) - 1`
-[ "$stable_ver_point" ] && \
-	stable_ver_prev=$(cat /tmp/.release.txt| grep -oE "4\.${stable_ver_point}\.[0-9]+" | tail -n 1)
-
-# Determine any already installed tool versions
-which openshift-install >/dev/null 2>&1 && cur_ver=$(openshift-install version | grep ^openshift-install | egrep -o "[0-9]+\.[0-9]+\.[0-9]+")
-
-# If openshift-install is already installed, then offer that version also
-[ "$cur_ver" ] && or_ret="or hit Return " && default_ver=$cur_ver
-
-target_ver=
-while ! echo "$target_ver" | egrep -q "^[0-9]+\.[0-9]+\.[0-9]+" 
+while [ "$*" ] 
 do
-	[ "$stable_ver" ] && echo -e "OpenShift latest stable version is: \t\t\t$stable_ver (s)" && or_s="or (s) "
-	[ "$stable_ver_point" ] && echo -e "OpenShift latest stable (prev) version is: \t\t$stable_ver_prev (p)" && or_p="or (p) "
-	[ "$cur_ver" ] && echo -e "Current installed version of 'openshift-install' is: \t$cur_ver (Return)"
-
-	echo
-	echo    "Which version of OpenShift do you want to install?"
-	echo -n "Enter version $or_s$or_p$or_ret [$default_ver]: "
-
-	read target_ver
-	[ ! "$target_ver" ] && target_ver=$default_ver
-	[ "$target_ver" = "s" ] && target_ver=$stable_ver
-	[ "$target_ver" = "p" ] && target_ver=$stable_ver_prev
+	if [ "$1" = "--debug" -o "$1" = "-d" ]; then
+		export DEBUG_ABA=1
+		set -x
+		shift 
+	elif [ "$1" = "--version" -o "$1" = "-v" ]; then
+		shift 
+		echo $1 | egrep -o "[0-9]+\.[0-9]+\.[0-9]+" > target-ocp-version.conf
+		target_ver=$(cat target-ocp-version.conf)
+		shift 
+		auto_ver=1
+	elif [ "$1" = "--vmware" -o "$1" = "--vmw" ]; then
+		shift 
+		[ -s $1 ] && cp $1 vmware.conf
+		auto_vmw=1
+		shift 
+	fi
 done
 
-echo "$target_ver" > target-ocp-version.conf
+# Include aba bin path and common scripts
+export PATH=$PWD/bin:$PATH
+
+if [ ! "$auto_ver" ]; then
+	cat message.txt
+
+	############
+	# Determine OCP version 
+
+	echo -n "Looking up OpenShift release versions ..."
+
+	if ! curl -sL https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/release.txt > /tmp/.release.txt; then
+		echo "Error: Cannot access mirror.openshift.com"
+		exit 1
+	fi
+
+	## Get the latest stable OCP version number, e.g. 4.14.6
+	stable_ver=$(cat /tmp/.release.txt | egrep -o "Version: +[0-9]+\.[0-9]+\.[0-9]+" | awk '{print $2}')
+	default_ver=$stable_ver
+
+	# Extract the previous stable point version, e.g. 4.13.23
+	stable_ver_point=`expr $(echo $stable_ver | grep ^4 | cut -d\. -f2) - 1`
+	[ "$stable_ver_point" ] && \
+		stable_ver_prev=$(cat /tmp/.release.txt| grep -oE "4\.${stable_ver_point}\.[0-9]+" | tail -n 1)
+
+	# Determine any already installed tool versions
+	which openshift-install >/dev/null 2>&1 && cur_ver=$(openshift-install version | grep ^openshift-install | egrep -o "[0-9]+\.[0-9]+\.[0-9]+")
+
+	# If openshift-install is already installed, then offer that version also
+	[ "$cur_ver" ] && or_ret="or currently installed version " && default_ver=$cur_ver
+
+	tput el1
+	tput cr
+	sleep 0.5
+
+	echo    "Which version of OpenShift do you want to install?"
+
+	target_ver=
+	#while ! echo "$target_ver" | egrep -q "^[0-9]+\.[0-9]+\.[0-9]+"
+	while true
+	do
+		# Exit loop if release version exists
+		if echo "$target_ver" | egrep -q "^[0-9]+\.[0-9]+\.[0-9]+"; then
+			if curl -sIL -o /dev/null -w "%{http_code}\n" https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/$target_ver/release.txt | grep -q ^200$; then
+				break
+			else
+				echo "Error: Failed to find release $target_ver"
+			fi
+		fi
+
+		#[ "$stable_ver" ] && echo -e "OpenShift latest stable version is: \t\t\t$stable_ver (s)" && or_s="or $stable_ver (s) "
+		#[ "$stable_ver_point" ] && echo -e "OpenShift latest stable (prev) version is: \t\t$stable_ver_prev (p)" && or_p="or $stable_ver_prev (p) "
+		[ "$stable_ver" ] && or_s="or $stable_ver (latest) "
+		[ "$stable_ver_point" ] && or_p="or $stable_ver_prev (previous) "
+		#[ "$cur_ver" ] && echo -e "Current installed version of 'openshift-install' is: \t$cur_ver"
+
+		echo -n "Enter version $or_s$or_p$or_ret(l/p/Ret) [$default_ver]: "
+
+		read target_ver
+		[ ! "$target_ver" ] && target_ver=$default_ver
+		[ "$target_ver" = "s" ] && target_ver=$stable_ver
+		[ "$target_ver" = "p" ] && target_ver=$stable_ver_prev
+	done
+
+	echo "$target_ver" > target-ocp-version.conf
+
+fi
 
 ############
 # vmware.conf
-
-if [ ! -s vmware.conf ]; then
-	echo
-	echo -n "Do you want to deploy to VMware (vSphere or ESXi)? (y/n) [y]: "
-	read yn
-	[ ! "$yn" -o "$yn" = "y" ] && make vmware.conf
+if [ ! "$auto_vmw" ]; then
+	if [ ! -s vmware.conf ]; then
+		#echo
+		#echo -n "Do you want to deploy to VMware (vSphere or ESXi)? (y/n) [y]: "
+		#read yn
+		#[ ! "$yn" -o "$yn" = "y" ] && make vmware.conf
+		make vmware.conf
+	fi
 fi
 
 # Install the main rpms that are needed
 sudo dnf install podman make jq bind-utils nmstate net-tools skopeo python3 python3-jinja2 -y >/dev/null 2>&1
 
 # Set up the CLIs
-[ "$target_ver" != "$cur_ver" ] && make -C cli ocp_target_ver=$target_ver all
+#[ "$target_ver" != "$cur_ver" ] && make -C cli ocp_target_ver=$target_ver all
+make -C cli ocp_target_ver=$target_ver 
 
-############
-# Offer next steps
-echo
-echo "----------------------------------------------------------------------------------------"
-echo "Now run one of the following to configure the registry and download the needed software."
-echo
-echo "For a 'connected' installation:"
-echo "make sync       # Run on a 'connected bastion', to load the registry directly from the Internet."
-echo
-echo "For a dissconnected (or air-gapped) installation:"
-echo "make save       # First, run on a 'connected bastion', to 'save' the images from the Internet to local disk. Tar the *whole repo* to a thumb drive."
-echo "make load       # Run on a 'disconnected bastion' to load the saved images into a registry from the thumb drive."
-echo
-echo "See the README file for more information."
-
-echo 
-echo After the mirror is working and loaded, run one of the following:
-echo "make sno                      # Warning: please first edit the template file templates/aba-sno.conf to match your environment"
-echo "make compact                  # Warning: please first edit the template file templates/aba-compact.conf to match your environment"
-echo "make standard                 # Warning: please first edit the template file templates/aba-standard.conf to match your environment"
-echo "make cluster name=mycluster   # This will set up a standard cluster and allow you to edit the aba.conf configuration file."
-echo
+if [ ! "$auto_ver" -a ! "$auto_vmw" ]; then
+	############
+	# Offer next steps
+	cat message-next-steps.txt
+fi
 
