Hide dnf output

diff --git a/install b/install
--- a/install
+++ b/install
@@ -24,7 +24,8 @@ done
 
 if [ ${#missing_pkgs[@]} -gt 0 ]; then
 	# try our luck and to install ...
-	if ! dnf install ${missing_pkgs[*]} -y; then
+	echo "Installing required rpms: ${missing_pkgs[*]} (logging to .dnf-install.log). Please wait!"
+	if ! dnf install ${missing_pkgs[*]} -y >.dnf-install.log 2>&1; then
 		echo
 		echo "Error installing missing required pkgs: ${missing_pkgs[*]}" >&2
 		echo "Please install the correct rpm packages (${missing_pkgs[*]}) and try again." >&2
