Update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,7 +16,7 @@ if ! grep -q "Top level Makefile" Makefile; then
 		echo "Aba needs access to the Internet to clone the Aba repository."
 		exit 1
 	else
-		echo "Error fetching git repo from https://github.com" >&2
+		echo "Error fetching git repo from https://github.com/sjbylo/aba.git" >&2
 
 		exit 1
 	fi
