Various ux changes and fixes after testing

diff --git a/install b/install
--- a/install
+++ b/install
@@ -9,7 +9,7 @@ branch=main
 
 cd $(dirname $0)
 
-# Only want to use git on the workstation
+# Only want to use git on the workstation with Internet access
 if [ ! -f .bundle ]; then
 	if ! which git 2>/dev/null >&2; then
 		echo "Please install git and try again!"
@@ -18,10 +18,10 @@ if [ ! -f .bundle ]; then
 	fi
 fi
 
-# If we are installing by pipeing into bash
+# If we are installing by piping into bash
 if ! grep -q "Top level Makefile" Makefile 2>/dev/null; then
 	if ! git clone -b $branch https://github.com/${repo}.git; then
-		echo "Error fetching git repo from https://github.com/${repo}.git" >&2
+		echo "Error fetching git repo from https://github.com/${repo}.git (branch: $branch)" >&2
 
 		exit 1
 	fi
@@ -33,7 +33,7 @@ fi
 
 if [ -x scripts/aba.sh ]; then
 	if [[ "$PATH" =~ "/usr/local/bin:" ]]; then
-		[ -s "/usr/local/bin/aba" ] && action=updated || action=installed
+		[ -s "/usr/local/bin/aba" ] && action="updated to /usr/local/bin" || action="installed to /usr/local/bin"
 
 		if ! sudo cp -p scripts/aba.sh /usr/local/bin/aba; then
 			echo "Cannot install $PWD/scripts/aba.sh!  Please copy the script file into your \$PATH." >&2
@@ -42,7 +42,7 @@ if [ -x scripts/aba.sh ]; then
 		fi
 
 	elif [[ "$PATH" =~ "$HOME/bin:" ]]; then
-		[ -s "$HOME/bin/aba" ] && action=updated || action=installed
+		[ -s "$HOME/bin/aba" ] && action="updated to ~/bin" || action="installed to ~/bin"
 
 		mkdir -p $HOME/bin
 
@@ -57,7 +57,7 @@ if [ -x scripts/aba.sh ]; then
 		exit 1
 	fi
 
-	[ ! "$quiet" ] && echo "Aba has been $action to /usr/local/bin/aba"
+	[ ! "$quiet" ] && echo "Aba has been $action"
 	[ ! "$quiet" ] && echo "Run: cd aba; aba"
 	[ ! "$quiet" ] && echo "Run: cd aba -h for help or see the README.md file"
 
