fix

diff --git a/install b/install
--- a/install
+++ b/install
@@ -52,8 +52,11 @@ fi
 # If we are installing by piping into bash
 if ! grep -q "Top level Makefile" Makefile 2>/dev/null; then
 	if ! git clone -b $branch https://github.com/${repo}.git; then
+		if ! git checkout $branch; then
+			echo "Error checking out git branch $branch" >&2
+			exit 1
+		fi
 		echo "Error fetching git repo from https://github.com/${repo}.git (branch: $branch)" >&2
-
 		exit 1
 	fi
 
