Create new branch [opt]

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,15 +1,16 @@
 #!/bin/bash
 # Simple Aba installer.  Copy aba command somewhere into the $PATH
 
+PREFIX=/opt/aba
+
 uname -o | grep -q "^Darwin$" && echo "Install aba on RHEL or Fedora. Most tested is RHEL 9 (no oc-mirror for Mac OS!)." >&2 && exit 1
 
-# We need git, which, id, diff commands (not always available in a container) ... 
-# the other rpm packages are copied from templates/rpms-external.txt which isn't available yet!
+# We need: git, which, id, diff commands (not always available in a container) ... 
+# the other rpm packages have been copied here (hard coded) from templates/rpms-external.txt which isn't available yet!
 required_pkgs=(which file hostname diffutils git make jq python3-jinja2 python3-pyyaml ncurses)
 missing_pkgs=()
 
 for pkg in "${required_pkgs[@]}"; do
-	#if ! which "$pkg" >/dev/null; then
 	if ! rpm -q "$pkg" >/dev/null; then
 		missing_pkgs+=("$pkg")
 	fi
@@ -36,9 +37,6 @@ if ! which id >/dev/null 2>&1; then
 
 	exit 1
 fi
-
-##SUDO=
-##which sudo 2>/dev/null >&2 && SUDO=sudo
 
 # Check sudo or root access 
 # If user is not root
@@ -74,14 +72,15 @@ msg=
 [ "$1" ] && branch="$1"
 [ "$2" ] && repo="$2"
 
-is_repo_available() {
-	[ -s ./scripts/aba.sh -a -x ./scripts/aba.sh ] && return 0
+is_repo_installed() {
+	[ -s $PREFIX/scripts/aba.sh -a -x $PREFIX/scripts/aba.sh ] && return 0
 	# If curl is used...
 	[ "$0" = "--" -o "$0" = "bash" ] && return 1
 
-	# We must have the repo, cd into it...
-	cd $(dirname $0)
-	return 0
+#	# We must have the repo, cd into it...
+#	#cd $(dirname $0)
+#	cd $PREFIX  # FIXME: Needed?
+	return 1
 }
 
 download_repo() {
@@ -93,11 +92,15 @@ download_repo() {
 
 	if ! grep -q "Top level Makefile" Makefile 2>/dev/null; then
 		echo Cloning aba with: "git clone -b $branch https://github.com/${repo}.git" >&2
-		if ! git clone -b $branch https://github.com/${repo}.git; then
+		rm -rf ~/.aba
+		if ! git clone -b $branch https://github.com/${repo}.git ~/.aba; then
 			echo "Error fetching git repo from https://github.com/${repo}.git (branch: $branch)" >&2
 
 			exit 1
 		fi
+
+		rm -rf /opt/aba
+		$SUDO cp -rp ~/.aba /opt/aba
 
 		echo
 		[ "$PWD" = "/" ] && echo "Cloned aba branch $branch into /aba" >&2 || echo "Cloned aba branch $branch into $PWD/aba" >&2
@@ -105,24 +108,27 @@ download_repo() {
 	fi
 }
 
+#FIXME: Used?
 aba_is_installed() {
 	# if aba is not installed then consider no current ver
 	which aba >/dev/null 2>&1 && return 0 || return 1
 }
 
 get_repo_ver() {
-	grep "^ABA_VERSION=" ./scripts/aba.sh | cut -d= -f2 | grep -oE "^[0-9]{14}$"
+	grep "^ABA_VERSION=" $PREFIX/scripts/aba.sh | cut -d= -f2 | grep -oE "^[0-9]{14}$"
 }
 
-if ! is_repo_available; then
+cd $(dirname $PREFIX)
+
+if ! is_repo_installed; then
 	download_repo
 	msg="Run: 'cd aba; aba' or see the README.md file"
 fi
 
 # Sanity check ...
-[ ! -x scripts/aba.sh ] && echo "Abort: Incomplete aba repo! aba script not found in $PWD/scripts/aba.sh" >&2 && exit 1
+[ ! -x $PREFIX/scripts/aba.sh ] && echo "Abort: Incomplete aba repo! aba script not found in $PREFIX/scripts/aba.sh" >&2 && exit 1
 
-source scripts/include_all.sh
+source $PREFIX/scripts/include_all.sh
 install_rpms $(cat templates/rpms-external.txt)
 
 # Install aba somewhere into the $PATH 
@@ -154,17 +160,17 @@ do
 		[ "$d" = "$HOME/bin" -a ! -d $d ] && mkdir -p $d
 
 		# Now, try to install aba
-		if $SUDO cp -p scripts/aba.sh $d/aba; then
+		if $SUDO cp -p $PREFIX/scripts/aba.sh $d/aba; then
 			$SUDO chmod +x $d/aba
 			[ ! "$quiet" ] && echo aba has been $action to $d/aba >&2
-			[ ! "$quiet" -a -n "$msg" ] && source scripts/include_all.sh && echo_yellow "$msg" >&2
+			[ ! "$quiet" -a -n "$msg" ] && source $PREFIX/scripts/include_all.sh && echo_yellow "$msg" >&2
 
 			exit $ret  # Success
 		fi
 	fi
 done
 
-[ ! "$quiet" ] && echo "Cannot install $PWD/scripts/aba.sh!  Please copy it into your \$PATH and name it 'aba'." >&2
+[ ! "$quiet" ] && echo "Cannot install $PREFIX/scripts/aba.sh!  Please copy it into your \$PATH and name it 'aba'." >&2
 
 exit 1
 
