Install fix

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,10 @@
 #!/bin/bash -e
 # Simple Aba installer.  Copy aba command somewhere into the $PATH
 
+repo=sjbylo/aba
 branch=main
+[ "$1" ] && repo="$1"
+[ "$2" ] && branch="$2"
 
 cd $(dirname $0)
 
@@ -16,8 +19,8 @@ fi
 
 # If we are installing by pipeing into bash
 if ! grep -q "Top level Makefile" Makefile 2>/dev/null; then
-	if ! git clone -b $branch https://github.com/sjbylo/aba.git; then
-		echo "Error fetching git repo from https://github.com/sjbylo/aba.git" >&2
+	if ! git clone -b $branch https://github.com/${repo}.git; then
+		echo "Error fetching git repo from https://github.com/${repo}.git" >&2
 
 		exit 1
 	fi
