Test for rom packages better, if the pkg name is clear

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,31 +3,39 @@
 
 uname -o | grep -q "^Darwin$" && echo "Install aba on RHEL or Fedora. Most tested is RHEL 9 (no oc-mirror for Mac OS!)." >&2 && exit 1
 
+required_pkgs=(which git file)
+missing_pkgs=()
+
 # We need git, which and id commands ....
-if ! rpm -q which >/dev/null 2>&1; then
-	if ! dnf install which -y; then
-		echo "Error installing missing package: make" >&2
-		echo "Please install it and try again." >&2 
+#if ! rpm -q which >/dev/null 2>&1; then
+	#if ! dnf install which -y; then
+		#echo "Error installing missing package: make" >&2
+		#echo "Please install it and try again." >&2 
+		#exit 1
+	#fi
+#fi
+
+for pkg in "${required_pkgs[@]}"; do
+	#if ! which "$pkg" >/dev/null; then
+	if ! rpm -q "$pkg" >/dev/null; then
+		missing_pkgs+=("$pkg")
+	fi
+done
+
+if [ ${#missing_pkgs[@]} -gt 0 ]; then
+	# try our luck and to install ...
+	if ! dnf install ${missing_pkgs[*]} -y; then
+		echo
+		echo "Error installing missing required pkgs: ${missing_pkgs[*]}" >&2
+		echo "Please install the correct rpm packages (${missing_pkgs[*]}) and try again." >&2
 		exit 1
 	fi
 fi
 
-required_commands=(git id file)
-missing_commands=()
+if ! which id >/dev/null 2>&1; then
+	echo "Please install the command 'id', usually in the coreutils package and try again." >&2
 
-for cmd in "${required_commands[@]}"; do
-	#if ! rpm -q "$cmd" >/dev/null; then
-	if ! which "$cmd" >/dev/null; then
-		missing_commands+=("$cmd")
-	fi
-done
-
-if [ ${#missing_commands[@]} -gt 0 ]; then
-	if ! sudo dnf install git file -y; then
-		echo "Missing required commands: ${missing_commands[*]}" >&2
-		echo "Please install the correct rpm packages (coreutils and/or git) and try again." >&2
-		exit 1
-	fi
+	exit 1
 fi
 
 SUDO=
